default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: watervideo_development
test:
  <<: *default
  database: watervideo_test
production:
  <<: *default
  database: watervideo_production
  username: watervideo
  password: <%= ENV['WATERVIDEO_DATABASE_PASSWORD'] %>
