default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: video-store_development
test:
  <<: *default
  database: video-store_test
production:
  <<: *default
  database: video-store_production
  username: video-store
  password: <%= ENV['VIDEO-STORE_DATABASE_PASSWORD'] %>
